name: Run Tests and a test build
on: [push, pull_request]


jobs:
  test-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run userscripts
        env:
          CI: false
